DjangoPythonProj/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forum/', include('forum.urls')),
]

forum/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import logout
from django.conf import settings


app_name = 'forum'

urlpatterns = [
    #/forum/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^login/$', views.UserLoginView.as_view(), name='login'),

    url(r'^logout/$', logout, {'next_page': '/forum/'}, name='logout'),

    #/forum/title/
    url(r'^(?P<slug>([a-zA-Z0-9 ]+))/$', views.DetailView.as_view(), name='detail'),

    #/forum/topic/add/
    url(r'topic/add/$', views.TopicCreate.as_view(), name='topic-add'),

    url(r'^(?P<topic>([a-zA-Z0-9 ]+))/add-answer$', views.AnswerCreate.as_view(), name='answer-add')
]

forum/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
from django.urls import reverse


class Answer(models.Model):
    author = models.CharField(max_length=20)
    created_date = models.DateTimeField(default=datetime.now())
    text = models.TextField(default="")

    def __str__(self):
        return str(self.author) + str(self.created_date)


class Topic(models.Model):
    author = models.CharField(max_length=30)
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=datetime.now())
    visits_no = models.IntegerField(default=0)
    answers_no = models.IntegerField(default=0)
    last_answer_date = models.DateTimeField(blank=True, null=True)
    last_answer_author = models.CharField(max_length=30, default="Noone")
    text = models.TextField(default="")
    answers = models.ManyToManyField(Answer)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:detail', kwargs={'slug': self.title})

forum/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Answer


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class AnswerAddForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Answer
        fields =['text']


class TopicAddForm(forms.Form):
    title = forms.CharField(max_length=30)
    text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Answer
        fields = ['title', 'text']

forum/views.py
from django.http import Http404
from django.urls import reverse
from django.contrib.auth.models import User
from django.views import generic
from .models import Topic, Answer
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserRegistrationForm, UserLoginForm, AnswerAddForm, TopicAddForm
from datetime import datetime


class IndexView(generic.ListView):
    template_name = 'forum/index.html'
    context_object_name = 'all_topics'

    def get_queryset(self):
        return Topic.objects.all()


class DetailView(generic.DeleteView):
    model = Topic
    slug_field = 'title'
    slug_url_kwarg = 'slug'
    template_name = 'forum/detail.html'

    def get_queryset(self):
        title = self.kwargs['slug']
        t = Topic.objects.get(title=title)
        t.visits_no += 1
        t.save()
        return Topic.objects.filter(title=title)


class TopicCreate(View):
    template_name = 'forum/topic_form.html'
    model = Topic
    form_class = TopicAddForm
    fields = ['author', 'title', 'text']


    # display blank form
    def get(self, request):
        if request.user.is_authenticated:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('forum:login')

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            # clean (normalized) data

            author = User.objects.get(username=self.request.user.username)
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            top = Topic.objects.filter(title=title)
            print(top)
            if len(top) == 1:
                raise Http404("Temat o takim tytule już istenieje")

            t = Topic(author=author, title=title, text=text)
            t.save()

            # returns User objects if credentials are correct
            return redirect(reverse('forum:detail', kwargs={'slug': title}))

        return render(request, self.template_name, {'form': form})


class AnswerCreate(View):
    model = Answer
    fields = ['author', 'text']
    form_class = AnswerAddForm
    template_name = 'forum/answer_form.html'

    # display blank form
    def get(self, request, topic):
        if request.user.is_authenticated:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('forum:login')

    # process form data
    def post(self, request, topic):
        form = self.form_class(request.POST)

        if form.is_valid():

            # clean (normalized) data

            author = User.objects.get(username=self.request.user.username)
            print(author.username)
            text = form.cleaned_data['text']
            a = Answer(author=author, text=text)
            a.save()
            t = Topic.objects.get(title=topic)
            t.answers_no += 1
            t.visits_no -= 1
            t.last_answer_date = datetime.now()
            t.last_answer_author = str(author)
            t.answers.add(a)
            t.save()

            # returns User objects if credentials are correct
            return redirect(reverse('forum:detail', kwargs={'slug': topic}))

        return render(request, self.template_name, {'form': form})


class UserFormView(View):
    form_class = UserRegistrationForm
    template_name = 'forum/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #clean (normalized) data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('forum:index')

        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'forum/login_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # clean (normalized) data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('forum:index')

        return render(request, self.template_name, {'form': form})

forum/templates/forum/answer_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class = "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/forum/">Forum</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/forum/#">
                        <span class="" aria-hidden="true"></span>&nbsp; New Topic
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'forum:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block title %} Add a New Answer {% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forum/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-t col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

forum/templates/forum/detail.html
<!-- Loads the path to static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class = "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/forum/">Forum</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{ request.get_full_path }}add-answer">
                        <span class="" aria-hidden="true"></span>&nbsp; Add Answer
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'forum:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>




<!-- Logic -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>
        Topic: {{ topic.title }}    <br>     Author: {{ topic.author }} <br>
        <div style="width: 80%; text-indent: 5em; text-align: justify; margin-left: 70px;">
            <h5>
                {{ topic.text }} <br><br>
            </h5>
        </div>
        <ul>
            {% for answer in topic.answers.all %}
                <h5>
                    {{ answer.author }}           {{ answer.created_date }} <br>
                    <div style="width: 80%; text-indent: 5em; text-align: justify; margin-left: 70px;">
                    {{ answer.text }} <br><br>
                    </div>
                </h5>
            {% endfor %}
        </ul>
    </h3>
</body>
</html>

forum/templates/forum/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"> {{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{%  endfor %}

forum/templates/forum/index.html
<!-- Loads the path to static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class = "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/forum/">Forum</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/forum/topic/add/">
                        <span class="" aria-hidden="true"></span>&nbsp; New Topic
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'forum:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- Logic -->

{% if object_list %}
    <ul>
        <h2> Topics here </h2>
        {% for topic in all_topics %}
        <li><h3><a href="/forum/{{ topic.title }}/">{{ topic.title }} </a></h3></li>
        <h4>Number of visits: {{ topic.visits_no }} Last answer author: {{ topic.last_answer_author }}</h4> <br>
        <h4>Created {{ topic.created_date }}</h4>
        {% endfor %}
    </ul>
{% else %}
    <h3> No topics here</h3>
{% endif %}

forum/templates/forum/login_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class = "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/forum/">Forum</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

{#            <ul class="nav navbar-nav">#}
{#                <li class="active">#}
{#                    <a href="/forum/#">#}
{#                        <span class="" aria-hidden="true"></span>&nbsp; New Topic#}
{#                    </a>#}
{#                </li>#}
{#            </ul>#}
{##}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li class="">#}
{#                    <a href="/forum/">#}
{#                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout#}
{#                    </a>#}
{#                </li>#}
{#            </ul>#}
        </div>
    </div>
</nav>


<!-- Logic -->

{% block title %} Login {% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> Login </h3>
                    {% if error_message %}
                        <p><strong>{{ error_mesage }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forum/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-t col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                                <a href="/forum/register" class="btn btn-success">Register</a>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

forum/templates/forum/registration_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class = "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/forum/">Forum</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/forum/#">
                        <span class="" aria-hidden="true"></span>&nbsp; New Topic
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-- Logic -->

{% block title %} Register {% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> Create a New Account </h3>
                    {% if error_message %}
                        <p><strong>{{ error_mesage }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forum/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-t col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

forum/templates/forum/topic_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />


<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class = "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/forum/">Forum</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/forum/#">
                        <span class="" aria-hidden="true"></span>&nbsp; New Topic
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'forum:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block title %} Add a New Topic {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forum/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-t col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}